/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RunsIndexRouteImport } from './routes/runs/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as PipelinesIndexRouteImport } from './routes/pipelines/index'
import { Route as AgentsIndexRouteImport } from './routes/agents/index'
import { Route as SkillsGenerateRouteImport } from './routes/skills.generate'
import { Route as RunsRunIdRouteImport } from './routes/runs/$runId'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects/$projectId'
import { Route as PipelinesPipelineIdRouteImport } from './routes/pipelines/$pipelineId'
import { Route as McpConfigureRouteImport } from './routes/mcp.configure'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AgentsAgentIdRouteImport } from './routes/agents/$agentId'

const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsIndexRoute = RunsIndexRouteImport.update({
  id: '/runs/',
  path: '/runs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelinesIndexRoute = PipelinesIndexRouteImport.update({
  id: '/pipelines/',
  path: '/pipelines/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsGenerateRoute = SkillsGenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => SkillsRoute,
} as any)
const RunsRunIdRoute = RunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelinesPipelineIdRoute = PipelinesPipelineIdRouteImport.update({
  id: '/pipelines/$pipelineId',
  path: '/pipelines/$pipelineId',
  getParentRoute: () => rootRouteImport,
} as any)
const McpConfigureRoute = McpConfigureRouteImport.update({
  id: '/configure',
  path: '/configure',
  getParentRoute: () => McpRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentIdRoute = AgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRouteWithChildren
  '/memory': typeof MemoryRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/skills': typeof SkillsRouteWithChildren
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/mcp/configure': typeof McpConfigureRoute
  '/pipelines/$pipelineId': typeof PipelinesPipelineIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/skills/generate': typeof SkillsGenerateRoute
  '/agents/': typeof AgentsIndexRoute
  '/pipelines/': typeof PipelinesIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/runs/': typeof RunsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRouteWithChildren
  '/memory': typeof MemoryRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/skills': typeof SkillsRouteWithChildren
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/mcp/configure': typeof McpConfigureRoute
  '/pipelines/$pipelineId': typeof PipelinesPipelineIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/skills/generate': typeof SkillsGenerateRoute
  '/agents': typeof AgentsIndexRoute
  '/pipelines': typeof PipelinesIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/runs': typeof RunsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRouteWithChildren
  '/memory': typeof MemoryRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/skills': typeof SkillsRouteWithChildren
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/mcp/configure': typeof McpConfigureRoute
  '/pipelines/$pipelineId': typeof PipelinesPipelineIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/skills/generate': typeof SkillsGenerateRoute
  '/agents/': typeof AgentsIndexRoute
  '/pipelines/': typeof PipelinesIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/runs/': typeof RunsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/login'
    | '/mcp'
    | '/memory'
    | '/settings'
    | '/setup'
    | '/skills'
    | '/agents/$agentId'
    | '/auth/callback'
    | '/mcp/configure'
    | '/pipelines/$pipelineId'
    | '/projects/$projectId'
    | '/runs/$runId'
    | '/skills/generate'
    | '/agents/'
    | '/pipelines/'
    | '/projects/'
    | '/runs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/login'
    | '/mcp'
    | '/memory'
    | '/settings'
    | '/setup'
    | '/skills'
    | '/agents/$agentId'
    | '/auth/callback'
    | '/mcp/configure'
    | '/pipelines/$pipelineId'
    | '/projects/$projectId'
    | '/runs/$runId'
    | '/skills/generate'
    | '/agents'
    | '/pipelines'
    | '/projects'
    | '/runs'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/login'
    | '/mcp'
    | '/memory'
    | '/settings'
    | '/setup'
    | '/skills'
    | '/agents/$agentId'
    | '/auth/callback'
    | '/mcp/configure'
    | '/pipelines/$pipelineId'
    | '/projects/$projectId'
    | '/runs/$runId'
    | '/skills/generate'
    | '/agents/'
    | '/pipelines/'
    | '/projects/'
    | '/runs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRouteWithChildren
  MemoryRoute: typeof MemoryRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  SkillsRoute: typeof SkillsRouteWithChildren
  AgentsAgentIdRoute: typeof AgentsAgentIdRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  PipelinesPipelineIdRoute: typeof PipelinesPipelineIdRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  RunsRunIdRoute: typeof RunsRunIdRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  PipelinesIndexRoute: typeof PipelinesIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  RunsIndexRoute: typeof RunsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/': {
      id: '/runs/'
      path: '/runs'
      fullPath: '/runs/'
      preLoaderRoute: typeof RunsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipelines/': {
      id: '/pipelines/'
      path: '/pipelines'
      fullPath: '/pipelines/'
      preLoaderRoute: typeof PipelinesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/generate': {
      id: '/skills/generate'
      path: '/generate'
      fullPath: '/skills/generate'
      preLoaderRoute: typeof SkillsGenerateRouteImport
      parentRoute: typeof SkillsRoute
    }
    '/runs/$runId': {
      id: '/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof RunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipelines/$pipelineId': {
      id: '/pipelines/$pipelineId'
      path: '/pipelines/$pipelineId'
      fullPath: '/pipelines/$pipelineId'
      preLoaderRoute: typeof PipelinesPipelineIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp/configure': {
      id: '/mcp/configure'
      path: '/configure'
      fullPath: '/mcp/configure'
      preLoaderRoute: typeof McpConfigureRouteImport
      parentRoute: typeof McpRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId': {
      id: '/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AgentsAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface McpRouteChildren {
  McpConfigureRoute: typeof McpConfigureRoute
}

const McpRouteChildren: McpRouteChildren = {
  McpConfigureRoute: McpConfigureRoute,
}

const McpRouteWithChildren = McpRoute._addFileChildren(McpRouteChildren)

interface SkillsRouteChildren {
  SkillsGenerateRoute: typeof SkillsGenerateRoute
}

const SkillsRouteChildren: SkillsRouteChildren = {
  SkillsGenerateRoute: SkillsGenerateRoute,
}

const SkillsRouteWithChildren =
  SkillsRoute._addFileChildren(SkillsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRouteWithChildren,
  MemoryRoute: MemoryRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  SkillsRoute: SkillsRouteWithChildren,
  AgentsAgentIdRoute: AgentsAgentIdRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  PipelinesPipelineIdRoute: PipelinesPipelineIdRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  RunsRunIdRoute: RunsRunIdRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  PipelinesIndexRoute: PipelinesIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  RunsIndexRoute: RunsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
