"""initial_postgres_schema

Revision ID: 4c9c86a8a7cd
Revises: 
Create Date: 2026-02-17 12:01:22.127298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c9c86a8a7cd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_app_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('app_name', sa.String(length=128), nullable=False),
    sa.Column('client_id', sa.String(length=128), nullable=False),
    sa.Column('webhook_secret', sa.String(length=256), nullable=False),
    sa.Column('private_key_path', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_id')
    )
    op.create_index('idx_github_app_config_app_id', 'github_app_config', ['app_id'], unique=False)
    op.create_table('loop_state',
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('step_id', sa.String(length=64), nullable=False),
    sa.Column('items', sa.Text(), nullable=False),
    sa.Column('current_index', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('run_id', 'step_id')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('repository', sa.Text(), nullable=True),
    sa.Column('default_pipeline_id', sa.String(length=128), nullable=True),
    sa.Column('completed_at', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('pipeline_id', sa.String(length=128), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('task_description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('outputs', sa.Text(), nullable=False),
    sa.Column('current_step_id', sa.String(length=64), nullable=True),
    sa.Column('human_context', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_pipeline_id'), 'runs', ['pipeline_id'], unique=False)
    op.create_table('webhook_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('delivery_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=True),
    sa.Column('installation_id', sa.String(length=64), nullable=True),
    sa.Column('repository_full_name', sa.String(length=256), nullable=True),
    sa.Column('repository_id', sa.Integer(), nullable=True),
    sa.Column('sender_login', sa.String(length=128), nullable=True),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('signature', sa.String(length=256), nullable=False),
    sa.Column('verified', sa.Integer(), nullable=False),
    sa.Column('processed', sa.Integer(), nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('received_at', sa.BigInteger(), nullable=False),
    sa.Column('processed_at', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('delivery_id')
    )
    op.create_index('idx_webhook_delivery', 'webhook_events', ['delivery_id'], unique=False)
    op.create_index('idx_webhook_event_type', 'webhook_events', ['event_type', 'action'], unique=False)
    op.create_index('idx_webhook_processed', 'webhook_events', ['processed', 'received_at'], unique=False)
    op.create_index('idx_webhook_repo', 'webhook_events', ['repository_full_name'], unique=False)
    op.create_table('webhook_secrets',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('installation_id', sa.String(length=64), nullable=True),
    sa.Column('secret_hash', sa.String(length=256), nullable=False),
    sa.Column('last_used_at', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('installation_id')
    )
    op.create_table('github_installation_states',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('state_token', sa.String(length=128), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('expires_at', sa.BigInteger(), nullable=False),
    sa.Column('used', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state_token')
    )
    op.create_index('idx_github_states_expires', 'github_installation_states', ['expires_at'], unique=False)
    op.create_index('idx_github_states_project', 'github_installation_states', ['project_id'], unique=False)
    op.create_index('idx_github_states_token', 'github_installation_states', ['state_token'], unique=False)
    op.create_table('kanban_columns',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('wip_limit', sa.Integer(), nullable=True),
    sa.Column('task_statuses', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_kanban_project', 'kanban_columns', ['project_id'], unique=False)
    op.create_table('knowledge',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('importance', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_knowledge_run', 'knowledge', ['run_id'], unique=False)
    op.create_table('outputs',
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('step_id', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=256), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('run_id', 'key')
    )
    op.create_index('idx_outputs_run', 'outputs', ['run_id'], unique=False)
    op.create_table('project_agents',
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('assigned_at', sa.BigInteger(), nullable=False),
    sa.Column('assigned_by', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'agent_id')
    )
    op.create_index('idx_project_agents_agent', 'project_agents', ['agent_id'], unique=False)
    op.create_index('idx_project_agents_project', 'project_agents', ['project_id'], unique=False)
    op.create_table('project_github',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('installation_id', sa.Integer(), nullable=False),
    sa.Column('repo_owner', sa.String(length=128), nullable=False),
    sa.Column('repo_name', sa.String(length=256), nullable=False),
    sa.Column('repo_full_name', sa.String(length=384), nullable=False),
    sa.Column('default_branch', sa.String(length=128), nullable=False),
    sa.Column('connected_at', sa.BigInteger(), nullable=False),
    sa.Column('connected_by', sa.String(length=128), nullable=True),
    sa.Column('last_push_at', sa.BigInteger(), nullable=True),
    sa.Column('last_sync_at', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('github_metadata', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_index('idx_project_github_active', 'project_github', ['is_active'], unique=False)
    op.create_index('idx_project_github_installation', 'project_github', ['installation_id'], unique=False)
    op.create_index('idx_project_github_project', 'project_github', ['project_id'], unique=False)
    op.create_index('idx_project_github_repo', 'project_github', ['repo_full_name'], unique=False)
    op.create_table('project_github_agents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('event_action', sa.String(length=64), nullable=True),
    sa.Column('filter_labels', sa.Text(), nullable=True),
    sa.Column('filter_file_patterns', sa.Text(), nullable=True),
    sa.Column('filter_authors', sa.Text(), nullable=True),
    sa.Column('auto_respond', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_github_agent_event', 'project_github_agents', ['event_type', 'event_action'], unique=False)
    op.create_index('idx_github_agent_project', 'project_github_agents', ['project_id'], unique=False)
    op.create_table('project_workflows',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('pipeline_id', sa.String(length=128), nullable=False),
    sa.Column('is_default', sa.Integer(), nullable=False),
    sa.Column('task_filter', sa.Text(), nullable=False),
    sa.Column('trigger', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_workflows_project', 'project_workflows', ['project_id'], unique=False)
    op.create_table('steps',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('step_id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=True),
    sa.Column('inputs', sa.Text(), nullable=False),
    sa.Column('outputs', sa.Text(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.BigInteger(), nullable=True),
    sa.Column('completed_at', sa.BigInteger(), nullable=True),
    sa.Column('human_context', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('run_id', 'step_id')
    )
    op.create_index('idx_steps_run', 'steps', ['run_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.String(length=8), nullable=False),
    sa.Column('assigned_agent', sa.String(length=128), nullable=True),
    sa.Column('workflow_id', sa.String(length=64), nullable=True),
    sa.Column('pipeline_id', sa.String(length=128), nullable=True),
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.Column('parent_task_id', sa.String(length=64), nullable=True),
    sa.Column('tags', sa.Text(), nullable=False),
    sa.Column('estimated_hours', sa.Float(), nullable=True),
    sa.Column('column_id', sa.String(length=64), nullable=False),
    sa.Column('column_position', sa.Integer(), nullable=False),
    sa.Column('metadata', sa.Text(), nullable=False),
    sa.Column('completed_at', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['column_id'], ['kanban_columns.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tasks_column', 'tasks', ['column_id'], unique=False)
    op.create_index('idx_tasks_project', 'tasks', ['project_id'], unique=False)
    op.create_index('idx_tasks_status', 'tasks', ['status'], unique=False)
    op.create_table('dependency_edges',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('from_task_id', sa.String(length=64), nullable=False),
    sa.Column('to_task_id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['from_task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_task_id', 'to_task_id', name='uq_dependency_edge')
    )
    op.create_index('idx_deps_from', 'dependency_edges', ['from_task_id'], unique=False)
    op.create_index('idx_deps_project', 'dependency_edges', ['project_id'], unique=False)
    op.create_index('idx_deps_to', 'dependency_edges', ['to_task_id'], unique=False)
    op.create_table('github_agent_triggers',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('agent_assignment_id', sa.String(length=64), nullable=False),
    sa.Column('webhook_event_id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('event_action', sa.String(length=64), nullable=True),
    sa.Column('repository_full_name', sa.String(length=384), nullable=True),
    sa.Column('trigger_reason', sa.Text(), nullable=True),
    sa.Column('task_id', sa.String(length=64), nullable=True),
    sa.Column('session_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('triggered_at', sa.BigInteger(), nullable=False),
    sa.Column('completed_at', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['agent_assignment_id'], ['project_github_agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['webhook_event_id'], ['webhook_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trigger_project', 'github_agent_triggers', ['project_id'], unique=False)
    op.create_index('idx_trigger_status', 'github_agent_triggers', ['status'], unique=False)
    op.create_index('idx_trigger_task', 'github_agent_triggers', ['task_id'], unique=False)
    op.create_index('idx_trigger_webhook', 'github_agent_triggers', ['webhook_event_id'], unique=False)
    op.create_table('task_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('pipeline_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.BigInteger(), nullable=True),
    sa.Column('completed_at', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_task_runs_task', 'task_runs', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_task_runs_task', table_name='task_runs')
    op.drop_table('task_runs')
    op.drop_index('idx_trigger_webhook', table_name='github_agent_triggers')
    op.drop_index('idx_trigger_task', table_name='github_agent_triggers')
    op.drop_index('idx_trigger_status', table_name='github_agent_triggers')
    op.drop_index('idx_trigger_project', table_name='github_agent_triggers')
    op.drop_table('github_agent_triggers')
    op.drop_index('idx_deps_to', table_name='dependency_edges')
    op.drop_index('idx_deps_project', table_name='dependency_edges')
    op.drop_index('idx_deps_from', table_name='dependency_edges')
    op.drop_table('dependency_edges')
    op.drop_index('idx_tasks_status', table_name='tasks')
    op.drop_index('idx_tasks_project', table_name='tasks')
    op.drop_index('idx_tasks_column', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('idx_steps_run', table_name='steps')
    op.drop_table('steps')
    op.drop_index('idx_workflows_project', table_name='project_workflows')
    op.drop_table('project_workflows')
    op.drop_index('idx_github_agent_project', table_name='project_github_agents')
    op.drop_index('idx_github_agent_event', table_name='project_github_agents')
    op.drop_table('project_github_agents')
    op.drop_index('idx_project_github_repo', table_name='project_github')
    op.drop_index('idx_project_github_project', table_name='project_github')
    op.drop_index('idx_project_github_installation', table_name='project_github')
    op.drop_index('idx_project_github_active', table_name='project_github')
    op.drop_table('project_github')
    op.drop_index('idx_project_agents_project', table_name='project_agents')
    op.drop_index('idx_project_agents_agent', table_name='project_agents')
    op.drop_table('project_agents')
    op.drop_index('idx_outputs_run', table_name='outputs')
    op.drop_table('outputs')
    op.drop_index('idx_knowledge_run', table_name='knowledge')
    op.drop_table('knowledge')
    op.drop_index('idx_kanban_project', table_name='kanban_columns')
    op.drop_table('kanban_columns')
    op.drop_index('idx_github_states_token', table_name='github_installation_states')
    op.drop_index('idx_github_states_project', table_name='github_installation_states')
    op.drop_index('idx_github_states_expires', table_name='github_installation_states')
    op.drop_table('github_installation_states')
    op.drop_table('webhook_secrets')
    op.drop_index('idx_webhook_repo', table_name='webhook_events')
    op.drop_index('idx_webhook_processed', table_name='webhook_events')
    op.drop_index('idx_webhook_event_type', table_name='webhook_events')
    op.drop_index('idx_webhook_delivery', table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_runs_pipeline_id'), table_name='runs')
    op.drop_table('runs')
    op.drop_table('projects')
    op.drop_table('loop_state')
    op.drop_index('idx_github_app_config_app_id', table_name='github_app_config')
    op.drop_table('github_app_config')
    # ### end Alembic commands ###
